{
 "title": "SCR Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "App", "query": { "query": "label_values(app)" } },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(up{app=\"${App}\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SCR Input Score",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(scr_module_input_score_bucket{pod=~\"${Pod}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SCR Output Score",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(scr_module_output_score_bucket{pod=~\"${Pod}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SCR Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(scr_module_execution_seconds_bucket{pod=~\"${Pod}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SCR Buffers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "scr_num_active{pod=~\"${Pod}\"}"
    },
    {
     "expr": "scr_num_idle{pod=~\"${Pod}\"}"
    }
   ]
  },
  {
   "title": "SCR System CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scr_system_cpu_time{pod=~\"${Pod}\"}"
    },
    {
     "expr": "scr_user_cpu_time{pod=~\"${Pod}\"}"
    }
   ]
  },
  {
   "title": "SCR Core Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scr_memory_used_bytes{pod=~\"${Pod}\"}"
    }
   ]
  },
  {
   "title": "SCR JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scr_jvm_max{pod=~\"${Pod}\"}"
    },
    {
     "expr": "scr_jvm_free{pod=~\"${Pod}\"}"
    },
    {
     "expr": "scr_jvm_total{pod=~\"${Pod}\"}"
    }
   ]
  }
 ]
}