{
 "title": "SCR Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SCR Input Score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(scr_module_input_score_bucket{instance=~\"${Instance}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SCR Output Score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(scr_module_output_score_bucket{instance=~\"${Instance}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SCR Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(scr_module_execution_seconds_bucket{instance=~\"${Instance}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SCR Buffers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "scr_num_active{instance=~\"${Instance}\"}"
    },
    {
     "expr": "scr_num_idle{instance=~\"${Instance}\"}"
    }
   ]
  },
  {
   "title": "SCR CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "scr_system_cpu_time{instance=~\"${Instance}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "scr_user_cpu_time{instance=~\"${Instance}\"}"
    }
   ]
  },
  {
   "title": "SCR Core Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scr_memory_used_bytes{instance=~\"${Instance}\"}"
    }
   ]
  },
  {
   "title": "SCR JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scr_jvm_max{instance=~\"${Instance}\"}"
    },
    {
     "expr": "scr_jvm_free{instance=~\"${Instance}\"}"
    },
    {
     "expr": "scr_jvm_total{instance=\"scr-echo:8080\"}"
    }
   ]
  }
 ]
}